Import numpy as refrence to np

In [14]:
import numpy as np

make a list and change into a numpy array

In [15]:
my_list = [42, 7, 89, 16, 34, 58, 3, 77, 25, 61]
#change the list into np array
np_list = np.array(my_list)
print(my_list)
print(type(my_list))
print(np_list)
print(type(np_list))


[42, 7, 89, 16, 34, 58, 3, 77, 25, 61]
<class 'list'>
[42  7 89 16 34 58  3 77 25 61]
<class 'numpy.ndarray'>


Perform different operation in list and numpy array

Operation in normal list

In [16]:
#operation perform in list
total = sum(my_list)
maximum = max(my_list)
minimum = min(my_list)
sorted_list = sorted(my_list)
sorted_desc = sorted(my_list , reverse =True)

print(f" total={total}\n maximun in list = {maximum}\n minimum in list = {minimum}\n sorted the list ={sorted_list}\n reversr sorted the list ={sorted_desc}")

 total=412
 maximun in list = 89
 minimum in list = 3
 sorted the list =[3, 7, 16, 25, 34, 42, 58, 61, 77, 89]
 reversr sorted the list =[89, 77, 61, 58, 42, 34, 25, 16, 7, 3]


Operation in numpy array

In [17]:
# operatinon 
np_total = np.sum(np_list)
np_maximum = np.max(np_list)
np_minimum = np.min(np_list)
np_sorted_list = np.sort(np_list)
np_mean = np.mean(np_list)
np_median = np.median(np_list)

print(f" total ={np_total}\n maximum in list={np_maximum}\n minimum in list={np_minimum}\n sorted the list={np_sorted_list}\nmean={np_mean}\nmedian={np_median}")

 total =412
 maximum in list=89
 minimum in list=3
 sorted the list=[ 3  7 16 25 34 42 58 61 77 89]
mean=41.2
median=38.0


Normal operation in numpy list or array (*,/,+,-)

In [18]:
np_list2 = np_list + np_list
np_list3 = np_list * 2
np_list4 = np_list - 4

print(f" normal list{np_list}\n sum = {np_list2}\n multiply by 2 = {np_list3} \n sub by 4 ={np_list4}")

 normal list[42  7 89 16 34 58  3 77 25 61]
 sum = [ 84  14 178  32  68 116   6 154  50 122]
 multiply by 2 = [ 84  14 178  32  68 116   6 154  50 122] 
 sub by 4 =[38  3 85 12 30 54 -1 73 21 57]


Create a NumPy 2darray Object perform varioua operation

create a 2d array and change into 2d numpy array

In [19]:
list2d =[[1, 2, 3, 4, 5],
         [6, 7, 8, 9, 10],
         [11, 12, 13, 14, 15]]
print(list2d)
np_list2d = np.array(list2d)
print(np_list2d)
print(type(np_list2d))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


TO find the what dimension array and find number of row and column of numpy array

In [20]:
# dimension of array
print(f"{np_list2d.ndim} dimension of numpy array")

# the number of row and coulumn in numpy array (row,column)
print(f"(row,column) = {np_list2d.shape}")

# print(list2d.shape)     we cannot used shape method in normal it only used in numpy list or array


2 dimension of numpy array
(row,column) = (3, 5)


Access the row ,element and column in numpy list or array 

Access the row

In [21]:
# access the row in the numpy list 
print(np_list2d[0])     # access the first row 
print(np_list2d[1])     # access the second row

# operation  [total no of row - 1]   [total no of row -2]
print(np_list2d[-1])    # access the last row from the list   
print(np_list2d[-2])    # access the second last row from the list 

# access the  row from normal list 
print(list2d[1])        # access the second row from normal list 
print(list2d[-2])       # access the second last row from normal list 

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[ 6  7  8  9 10]
[6, 7, 8, 9, 10]
[6, 7, 8, 9, 10]


Acess the element in two dimension array 

array_name [index_row,index_column]   
    index starting with zero 0

In [22]:
print(np_list2d)
print(f"(no of row , no of column )= {np_list2d.shape}")

print(f"access the first element in the row and column {np_list2d[0,0]}") # access the element in first row and first column
print(np_list2d[1,1])   # access the element in second row and second  column 
print(np_list2d[1,3])    # access the element in second row and fourth column


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(no of row , no of column )= (3, 5)
access the first element in the row and column 1
7
9


Access the column in the numpy list or array

array_name [ : ,colume index]



In [23]:
print(np_list2d[:,0])    # access the first column in the list
print(np_list2d[:,2])   # access the third column in the list
print(np_list2d[:,-1])   # access the last element in the list

[ 1  6 11]
[ 3  8 13]
[ 5 10 15]


Slicing arrays for one dimension array

 for slicing array one by one    
 array_name[start:end]

 fpe slicing array skip the element    
 array_name[start:end:step]  


In [24]:
arr = np.array([10, 20, 30, 40, 50, 60, 70 ,80])
print(arr[1:4])
print(arr[0:5:2])    # skip one element in the list
print(arr[: :3])     # slip two element in the list

[20 30 40]
[10 30 50]
[10 40 70]


Slicing arrays for two dimension array\

array_name[start_row:end_row, start_column:end_column]

 * start_row → Starting row index (inclusive)

 * end_row → Ending row index (exclusive)

 * start_column → Starting column index (inclusive)

 * end_column → Ending column index (exclusive)




In [25]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr2d[:,0])
print(arr2d[:2,:2])
print(arr2d[0:2, 1:3])  


[1 4 7]
[[1 2]
 [4 5]]
[[2 3]
 [5 6]]


Logical operation in numpy

logical_and( )

logical_or( )



In [26]:
array1 = [3, 17, 12, 8, 19, 6, 15]
array2 = [4, 9, 1, 18, 20, 5, 7]
np_array1 = np.array(array1)
np_array2 = np.array(array2)
print(np_array1<15)
print(np_array2<15)
print(np_array2[np_array2 < 15])
print(np.logical_and( np_array1<15 , np_array2 < 15))

print(np_array1[np.logical_and( np_array1>5 , np_array1 < 15)])


[ True False  True  True False  True False]
[ True  True  True False False  True  True]
[4 9 1 5 7]
[ True False  True False False  True False]
[12  8  6]
